- name: Check if private key exists
  stat:
    path: "{{ ansible_ssh_private_key_file }}"
  register: ssh_key_stat

- name: make sure ssh-key dir exists
  file:
    path: "inventory/keys"
    state: directory

- name: generate ssh-key pair on localhost
  command: ssh-keygen -b 2048 -t rsa -f "{{ ansible_ssh_private_key_file }}" -q -N ""
  when: ssh_key_stat.stat.exists == False

