- hosts: local
  roles:
    - variables

- hosts: k8s-cluster:children
  roles:
    - common

- hosts: kube-master
  roles:
    - precheck
    - master

- hosts: k8s-cluster:children
  roles:
    - node

- import_playbook: kubespray/cluster.yml

- hosts: kube-master
  roles:
    - nvidia

- import_playbook: glusterfs.yml
  when: enable_glusterfs

- import_playbook: aurora.yml
  when: enable_aurora
