---
kind: Service
apiVersion: v1
metadata:
  name: heketi
  labels:
    glusterfs: heketi-service
  annotations:
    description: Exposes Heketi Service
spec:
  selector:
    glusterfs: heketi-pod
  ports:
  - nodePort: 32393
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
