---

# Bind secondary network adapter
# ifconfig DPDK interface down
- name: Make DPDK interface down
  command: ifconfig {{ dpdk_iface }} down
  ignore_errors: True
  when: ovs_type == 'dpdk'

# Bind port
- name: Bind port
  shell: cd ~/ && {{ DPDK_DIR }}/usertools/dpdk-devbind.py --bind=igb_uio {{ dpdk_iface }}
  ignore_errors: True
  when: ovs_type == 'dpdk'

# Check port
- name: Check port
  shell: cd ~/ && {{ DPDK_DIR }}/usertools/dpdk-devbind.py --status
  when: ovs_type == 'dpdk'

