---

# echo 'vm.nr_hugepages=1024' | sudo tee /etc/sysctl.d/hugepages.conf
- name: Setting hugepage sizes
  command: echo 'vm.nr_hugepages=1024' | sudo tee /etc/sysctl.d/hugepages.conf
  when: ansible_os_family == 'Debian'

# mount -t hugetlbfs none /dev/hugepages
- name: Mount hugepages
  mount:
    path: /dev/hugepages
    src: none
    fstype: hugetlbfs
    state: present

# sysctl -w vm.nr_hugepages=1024
# Set vm.nr_hugepages to  in sysctl.conf
- sysctl:
    name: vm.nr_hugepages
    value: {{ nr_hugepages }}
    state: present
