---

- name: config-hugepages - Configure hugepages
  include_tasks: config-hugepages.yml

- name: dpdk - Install DPDK
  include_tasks: dpdk.yml

- name: setting-kmod - Linux Kernel module setting
  include_tasks: setting-kmod.yml
