- name: add glusterfs apt repository
  become: yes
  become_method: sudo 
  apt_repository:
    repo: "ppa:gluster/glusterfs-{{ glusterfs_version }}"
    state: present

- name: install glusterfs dependencies
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
  with_items:
    - "glusterfs-server"
    - "thin-provisioning-tools"
    - "lvm2"
    - "xfsprogs"

