---
kubernetes:
  version: 1.9.7
  cluster:
    masters:
    - node:
        hostname: node-1
        ip: 192.168.26.11
    - node:
        hostname: node-2
        ip: 192.168.26.12
    - node:
        hostname: node-3
        ip: 192.168.26.13
    nodes:
glusterFS:
  version: 3.13
  heketiTopology:
    clusters:
    - nodes:
      - node:
          zone: 1
          hostnames:
            manage:
            - 192.168.26.11
            storage:
            - 192.168.26.11
        devices:
        - /dev/sdb
      - node:
          zone: 2
          hostnames:
            manage:
            - 192.168.26.12
            storage:
            - 192.168.26.12
        devices:
        - /dev/sdb
      - node:
          zone: 3
          hostnames:
            manage:
            - 192.168.26.13
            storage:
            - 192.168.26.13
        devices:
        - /dev/sdb
