---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: slow-many
  labels:
    app: cv-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1
