- name: download cuda-8 and cudnn-6 deb
  get_url:
    url: "https://storage.googleapis.com/deep-learning-lib/{{ item }}.deb"
    dest: "{{ playbook_dir }}"
  with_items:
    - libcudnn6_6.0.21-1%2Bcuda8.0_amd64
    - libcudnn6-dev_6.0.21-1%2Bcuda8.0_amd64
    
- name: install cudnn-6
  apt:
    deb: "{{ playbook_dir}}/{{ item }}.deb"
  with_items:
    - libcudnn6_6.0.21-1%2Bcuda8.0_amd64
    - libcudnn6-dev_6.0.21-1%2Bcuda8.0_amd64
