- name: create registry config directory on master
  file:
    path: "{{ registry_config_dir }}"
    state: directory

- name: copy dockerhub mirror config file to master
  copy:
    src: templates/dockerhub-mirror-config.yml
    dest: "{{ registry_config_dir }}/dockerhub-mirror-config.yml"

- name: create registry data directory on master
  file:
    path: "{{ registry_dockerhub_volume_dir }}"
    state: directory

- name: make sure a registry container is running on master
  docker_container:
    name: "{{ registry_dockerhub_name }}"
    image: registry:2
    state: started
    restart_policy: always
    detach: yes
    privileged: yes
    published_ports:
      - "{{ registry_dockerhub_port }}:5000"
    volumes:
      - "{{ registry_dockerhub_volume_dir }}:/data/registry"
      - "{{ registry_config_dir }}/dockerhub-mirror-config.yml:/etc/docker/registry/config.yml"

- name: make sure a docker daemon.json exists
  copy:
    src: templates/docker-daemon.json
    dest: /etc/docker/daemon.json
    force: no

- name: configure dockerd to use private registry as dockerhub mirror cache
  command: jq '."registry-mirrors"[0] = "http://{{ registry_dockerhub }}"' /etc/docker/daemon.json > /etc/docker/daemon.json_tmp 
  
- name: replace docker daemon.json
  command: mv /etc/docker/daemon.json_tmp /etc/docker/daemon.json

- name: restart docker
  service:
    name: docker
    state: restarted

    # NOT NEEDED
    #- name: check docker registry availibility
    #  shell: curl -X GET localhost:{{ registry_dockerhub_port }}/v2/_catalog
    #  register: registry_catelog
    #
    #- debug: msg="{{ registry_catalog }}"
